name: Pull Request Merge Precondition

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - uses: psf/black@stable
        with:
          options: "--check --verbose"

      - uses: isort/isort-action@master
        with:
          configuration: "--check-only --diff"
          requirementsFiles: "requirements.txt"

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip install pytest-cov

      - name: check migrations
        run: |
          python manage.py migrate
          python manage.py makemigrations --check --dry-run

      - name: run pytest
        run: |
          pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=pyconkr ./ | tee pytest-coverage.txt

      #- name: Pytest coverage comment
      #  uses: MishaKav/pytest-coverage-comment@main
      #  with:
      #    pytest-coverage-path: ./pytest-coverage.txt
      #    junitxml-path: ./pytest.xml
